"""create tables again

Revision ID: b7210757cecf
Revises: ddc906058694
Create Date: 2026-02-04 17:06:18.461100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b7210757cecf'
down_revision: Union[str, Sequence[str], None] = 'ddc906058694'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('errors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('error_analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('error_id', sa.Integer(), nullable=False),
    sa.Column('probable_root_cause', sa.Text(), nullable=False),
    sa.Column('impact_assesment', sa.Text(), nullable=False),
    sa.Column('urgency', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('signals_used', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('immediate_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('deeper_investigation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('assumptions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['error_id'], ['errors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('error_id'),
    sa.UniqueConstraint('error_id', name='uq_error_analyses_error_id')
    )
    op.create_table('error_solutions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('error_id', sa.Integer(), nullable=False),
    sa.Column('code_fixes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('configuration_changes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('deployment_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rollback_plan', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['error_id'], ['errors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('error_id'),
    sa.UniqueConstraint('error_id', name='uq_error_solutions_error_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('error_solutions')
    op.drop_table('error_analyses')
    op.drop_table('errors')
    # ### end Alembic commands ###
